name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Markdown lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'
        # Если нужно «только предупреждать», раскомментируй строку ниже:
        # continue-on-error: true

      - name: YAML lint (workflows only)
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows
          # Мягкий режим, чтобы не падать на мелочах стиля:
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy:
                level: warning
        # Если нужно «только предупреждать», раскомментируй:
        # continue-on-error: true

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM (SPDX JSON)
        run: syft dir:. -o spdx-json > sbom.spdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
