name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Markdown
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'

      - name: Validate YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run dependency scan
        run: |
          sudo apt-get install -y curl
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft dir:. -o spdx-json > sbom.spdx.json
