---
name: CI

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Go tests
        run: |
          cd chain/x/bridge
          go mod tidy
          go test ./... -v

      - name: Run gosec
        uses: securego/gosec-action@v2
        with:
          args: ./...
        working-directory: chain/x/bridge

      - name: Markdown lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: "**/*.md"

      - name: YAML lint (workflows only)
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy:
                level: warning

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM (SPDX JSON)
        run: syft dir:. -o spdx-json > sbom.spdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
