---
name: Scorecard

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 6 * * 1"

# минимально необходимые права на уровне workflow
permissions:
  contents: read
  actions: read

jobs:
  analysis:
    runs-on: ubuntu-latest

    # необходимые права ТОЛЬКО для этого job
    permissions:
      security-events: write   # нужно для upload-sarif
      id-token: write          # нужно, если когда-нибудь включишь publish_results: true
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4

      - uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
