name: Scorecard
on:
  push:
  schedule:
    - cron: '0 6 * * 1'  # еженедельно
jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: results.sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
